# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: csi-provisioner-doplugin
  labels:
    app: csi-provisioner-doplugin
spec:
  selector:
    app: csi-provisioner-doplugin
  ports:
    - name: dummy
      port: 12345
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-provisioner-doplugin
spec:
  serviceName: "csi-provisioner-doplugin"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-provisioner-doplugin
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.2.0
          args:
            - "--provisioner=com.digitalocean.csi.dobs"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: digitalocean-csi-plugin
          image: digitalocean/do-csi-plugin:v0.0.1
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--token=$(DIGITALOCEAN_ACCESS_TOKEN)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: DIGITALOCEAN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dotoken
                  key: token
          # remove 'always' once we have a working image
          # imagePullPolicy: "IfNotPresent"
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
